### PR TITLE
fix: toString for `Str` and simplify Obj implementation

### LINKED ISSUE #227: Array.toString() doesn’t quote strings
```
    var jsonarray = JSON.Value.Array();

    var thearray = _validate_ipv4(str);

    for (var i=0; i<thearray.length; i++) {
        var thisstr = JSON.Value.String(thearray[i]);
        jsonarray.push(thisstr);
    }

    return jsonarray.toString();
```
This is yielding things like: `[leadingZeroes,3]`, which of course isn’t valid.

It looks like the writeString() from the Object writer just needs to be accessible inside the Array writer as well?

### PR DESCRIPTION
**Pull request by willemneal**
- fixes #227
When generating a JSON string `"` are required.

This also updates `obj.toString` to take advantage of virtual overloading to simplify calling child Value's `toString` method.

### CODE REVIEW

**Comment by willemneal** [comment]
@torch2424 Can't add you as a reviewer, but I think you can still review.

File: assembly/JSON.ts [hunk 1]
```diff
@@ -201,7 +201,7 @@ export class Str extends Value {
   }
 
   toString(): string {
-    return this._str;
+    return `"${this._str}"`;
```
Comment (torch2424) [inline assembly/JSON.ts:204]: Hmmmm, so the reason why I removed the quotes here, is because if you get a JSON string, it's extremely hard to tell when you log the string if the quotes are a part of the string, or just the output of the string. 

Could we perhaps add a new function like: `toJSONString()`, that way we can signify it is a string that will work in JSON, vs. the string representation of the value? I don't think that would break be a breaking change, but could allow us to fix this internally. Unless you at NEAR have a bunch of code using .toString directly expecting the quotes? 🤔

File: assembly/JSON.ts [hunk 2]
```diff
@@ -298,77 +298,39 @@ export class Arr extends Value {
...
-        // Check for null values
-        if (value == null || value.isNull) {
-          objs.push(keyValueString += "null");
-          continue;
-        }
-
-        // Cast to our proper type
-        if (value.isString) {
-          let castedValue = changetype<Str>(value);
-          keyValueString += '"' + castedValue.toString() + '"';
```
Comment (torch2424) [inline assembly/JSON.ts:326]: And this didn't solve the problem? Could you expand on what use case needs the string quotes where it is missing? 🤔

**Review by torch2424 — CHANGES_REQUESTED** [review]
Thanks for the PR! I mostly have questions around the use case, as I am a bit confused why the current solution doesn't already work (at least internally), unless you have some code that depends on the string with the quotes?

File: assembly/JSON.ts (hunk 2 above)
Comment (willemneal) [reply assembly/JSON.ts:326]: I'll address both your comments here.  The issue is that when we have a JSON Value and want to `stringify` it, `toString` it should produce a valid JSON string. According to the [spec](http://json.org/) JSON strings have quotations.  

So while this case solved it when generating an object's string value it doesn't fix it for arrays (see #227) and strings themselves.

Consider parsing the following string `"hello"`.  Since the parsing starts the string with `h` it doesn't know that it's parsing a string.  Wheras `` `"hello"` `` the first character is `"` which signals that the value is a string.

See: https://jsfiddle.net/93Lhfvu2/

As for how to get the real string value you added `valueOf` to access the internal string value.

Lastly I added the work of @kpeters-cbsi, which escapes internal `"`'s and other reserved characters.

Comment (torch2424) [reply assembly/JSON.ts:326]: @willemneal 

> The issue is that when we have a JSON Value and want to stringify it, use toString, it should produce a valid JSON string. According to the spec JSON strings have quotations.

Ah yes! Thanks for providing the spec! Deifnitely when we output JSON, Strings should have quotation marks. But, it doesn't say anything about the `toString()` function having to output these quotation marks.

I guess taking a step back, I'm not debating whether if the strings shoud have quotation marks. More of a question if `toString()` is the right function for this to happen. Especially since [AssemblyScript's stdlib String toString()](https://www.assemblyscript.org/stdlib/string.html#instance-members) does not output quotation marks. It could be extremely confusing... 😯 

> So while this comment's case solved it when generating an object's string value it doesn't fix it for arrays (see #227) and strings themselves.

Ah! Okay cool, so this is more of an internal issue than! If it's arrays that are broken, I would say that we update how Arrays are stringified, and make sure to place the quotes around the strings. And/Or, we add a new function the JSON String like: `toFormatString()`, which includes the quotation marks, and update wherver we are stringifying a string to use this fucntion instead. Again, particularly because it could be really confusing given we already have a pattern in the AS stdlib for `toString()` 😄 

> Consider parsing the following string "hello". Since the parsing starts the string with h it doesn't know that it's parsing a string. Whereas `"hello"` the first character is " which signals that the value is a string.

Totally, for parsing JSON, we definitely want the quotes there, but if we do what I described above, we should add the quotations at the right time when we generate JSON 😄 

> As for how to get the real string value you added valueOf to access the internal string value.

Yep! I wanted them to be redundant. I was trying to create patterns here, where you could get the primitive type with "valueOf", and a string representation with "toString", which could then be used as normal. 

> Lastly I added the work of @kpeters-cbsi, which escapes internal "'s and other reserved characters.

That's awesome you included their work! Thank you! 😄 🎉

**Review by torch2424 — CHANGES_REQUESTED** [review]

**Comment by willemneal** [comment]
> I guess taking a step back, I'm not debating whether if the strings shoud have quotation marks. More of a question if toString() is the right function for this to happen. Especially since AssemblyScript's stdlib String toString() does not output quotation marks. It could be extremely confusing... 😯

@torch2424 

I would argue that `Value.toString` should return a valid JSON string of that value, such that this string could be reparsed back into a `Value`. And `Str.toString` should include the `"` because it's a valid JSON string value.  Consider `JSON.parse(JSON.stringify("hello")).  In your case this would fail because `stringify` wouldn't produce a valid JSON string value.  It seems you want `toString` to wrap `Value.Str` in every case except itself.

However, if the issue really is the confusion with the name then perhaps `stringify` instead?  However, we would lose the ability to insert `Value`'s in template strings which rely on `toString`.  I was wanting to have the same API as `JSON.stringify`, would then require passing the format options with each internal call to `Value.stringify`. Though this could also be done with `toString` if we have default params.

I'm sorry we didn't have this conversation when you first proposed removing the `"`s.

**Comment by torch2424** [comment]
> I would argue that Value.toString should return a valid JSON string of that value, such that this string could be reparsed back into a Value. And Str.toString should include the " because it's a valid JSON string value. Consider JSON.parse(JSON.stringify("hello")). In your case this would fail because stringifywouldn't produce a valid JSON string value. It seems you wanttoStringto wrapValue.Str` in every case except itself.

Ah, so looking at: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#using_json.stringify , this should work, as it seems that `JSON.stringify('foo'); // '"foo"'` does create a new string, that has the quotes around it. So the library should definitely match that behavior. But, it doesn't neccesarily mean that our JSON string type `.toString()` function should include the quotes. In fact, what we may want to do, is when we are constructing out JSON, instead of using `.toString()` on all of our types, we should be using `JSON.stringify` (replacing my `toFormatString idea`). 😄 

> However, if the issue really is the confusion with the name then perhaps stringify instead? However, we would lose the ability to insert Value's in template strings which rely on toString. I was wanting to have the same API as JSON.stringify, would then require passing the format options with each internal call to Value.stringify. Though this could also be done with toString if we have default params.

I like this solution a lot! 😄 I think I came to the same solution above, and totally, using default params on toString, doing something like `toString(shouldFormatForJSON: boolean = false)`, I think would be cool!

> I'm sorry we didn't have this conversation when you first proposed removing the "s.

No worries! We have semver, so whatever we decide, it shouldn't break underneath our users 😄

**Review by torch2424 — COMMENTED** [review]
Ah! So everything looks fine in this PR, but just wanted to confirm here we wanted to completely rename `toString()` to `stringify()`? 🤔 

I thought we would be keeping `toString()` to convert our JSON types to their AS primitives as strings, and then we would add a `JSON.stringify`, to turn JSON values into their JSON friendly string equivalents? 🤔 

Le me know what you think! 😄

**Comment by willemneal** [comment]
@torch2424 Oh I thought we change `toString` to `stringify` to signal that it is the opposite of parse and produces a `JSON` string. And `valueOf` helps access the underlying AS which then could be `toString`ed.  I think having both `stringify` and `toString` could be confusing, but I'm not opposed to having both.

`JSON.stringify` should handle actual AS types and `JSON.Value`s which then calls `.stringify`.

**Comment by torch2424** [comment]
@willemneal 

> I think having both stringify and toString could be confusing, but I'm not opposed to having both.

I agree, it's not the most optimal! But, I think having both will make users pause, and understand which one they need from a UX perspective. And would be a better UX than having to work around whichever `toString` implementation we choose 😄

Plus, I think preserving so that `toString()` give a string without the quotes, and `stringify` producing JSON friendly strings (strings with the quotes) would be a patch, instead of a breaking change semver wise 😄 

Let me know if that sounds good to you! If so, I'd say just re-add all the toString stuff, and then this PR would be good to go? 😄

**Comment by willemneal** [comment]
@torch2424 Should be good to go!

File: assembly/JSON.ts [hunk 3]
```diff
@@ -134,64 +137,48 @@ export abstract class Value {
   }
 
   get isString(): boolean {
-    if (this instanceof Str) {
-      return true;
-    }
-    return false;
+    return this instanceof Str;
```
Comment (torch2424) [inline assembly/JSON.ts:140]: Thanks for cleaning this up 😄

**Review by torch2424 — APPROVED** [review]
Thank you SOOOOO much for working through this with me! This PR looks good to go to me! 😄 🎉
